function puuuush(varargin)
    % Copy the registration data generated by puuuu.sh here.
    % You can extract each part from the generated string.
    PUUUUSH_SERVER="https://puuuu.sh/";
    PUUUUSH_USER_ID="UPDATE_FROM_REGISTRATION";
    PUUUUSH_DEVICE_ID="UPDATE_FROM_REGISTRATION";
    PUUUUSH_DEVICE_SHARED_SECRET="UPDATE_FROM_REGISTRATION";

    % Don't change anything below this.
    
    puuuush_url=sprintf("%sdo/%s/%s", PUUUUSH_SERVER, PUUUUSH_USER_ID, PUUUUSH_DEVICE_ID);
    
    timestamp=floor(posixtime(datetime('now','TimeZone','local')));
    pushstr=sprintf("%d/", timestamp);

    for i=1:length(varargin)
       pushstr=sprintf("%s%s/", pushstr, dec2hex(unicode2native(varargin{i}, 'utf-8'))');
    end

    % Sign the request: 
    signature_raw=unicode2native(sprintf("%s/%s", PUUUUSH_DEVICE_SHARED_SECRET, pushstr), 'utf-8');
    md = java.security.MessageDigest.getInstance('SHA-224');
    sig=sprintf('%02x', typecast(md.digest(signature_raw), 'uint8'));
    
    url=sprintf("%s/%s/%s", puuuush_url, sig, pushstr);

    import matlab.net.*
    import matlab.net.http.*
    r = RequestMessage;
    resp=send(r, URI(url))
    % Print the output:
    resp.Body.Data
end
